5.2
htmlacademy-javascript/274941-keksobooking-22 pull request #8
Opened 2021-02-23 14:44 UTC by teclevel

2021-02-23 20:56 UTC, balesniy requested changes

2021-02-23 20:56 UTC, balesniy commented on js/activation-site.js
> +    formAdvertisement.classList.toggle('ad-form--disabled');
у методов toggle есть второй параметр - условие, которое управляет установкой-снятием

2021-02-23 20:56 UTC, balesniy commented on js/datum-initial.js
> +const Price = {
в перечислении поля просят оформить как константы - см https://up.htmlacademy.ru/javascript/22/criteries#b8

2021-02-23 20:56 UTC, balesniy commented on js/user-form.js
> +let priceHousing = document.querySelector('#price');
const

2021-02-23 20:56 UTC, balesniy commented on js/user-form.js
> +typeHousing.onchange = () => {
вместе с плейсхолдером нужно установить минимальную цену для валидации. для критерия единообразия лучше везде использовать addEventListener

2021-02-23 20:56 UTC, balesniy commented on js/user-form.js
> +    for(let i = 0; i < time1.length; i++){
у селектов есть value и selectedIndex, можно обойтись без цикла, см https://learn.javascript.ru/form-elements#select-i-option

2021-02-23 20:56 UTC, balesniy commented on js/util.js
> +const getValueMap = (map, name) => {
функция выглядит избыточной, повторяет базовый синтаксис

2021-02-24 13:43 UTC, teclevel commented on js/user-form.js
> +    for(let i = 0; i < time1.length; i++){
готово

2021-02-24 14:09 UTC, teclevel commented on js/util.js
> +const getValueMap = (map, name) => {
исправил

2021-02-24 18:18 UTC, teclevel commented on js/activation-site.js
> +    formAdvertisement.classList.toggle('ad-form--disabled');
исправил

2021-02-24 20:31 UTC, teclevel commented on js/user-form.js
> +  }
не понимаю, почему в значениях с квартирой и дворцом правило не срабатывает.

2021-02-24 20:31 UTC, teclevel commented on js/datum-initial.js
> +  bungalow: '0',
если так оформить?

2021-02-25 08:58 UTC, balesniy requested changes

2021-02-25 08:58 UTC, balesniy commented on js/datum-initial.js
> +  bungalow: '0',
посмотри на примеры в критерии, если сомневаешься, оформи как обычную переменную

2021-02-25 08:58 UTC, balesniy commented on js/user-form.js
> +  priceHousing.value = priceHousing.placeholder;
значение цены вводит пользователь, мы должны установить ему минимальное ограничение, priceHousing.min

2021-02-25 08:58 UTC, balesniy commented on js/user-form.js
> +  let minPrice = priceHousing.placeholder;
const

2021-02-25 08:58 UTC, balesniy commented on js/user-form.js
> +  }
в html хранятся строки, они сравниваются в алфавитном порядке, см https://learn.javascript.ru/comparison#sravnenie-strok

2021-02-25 20:47 UTC, merged